#!/usr/bin/env bash

NEW_EXT=".webm"

[[ ! $(type -P ffmpeg) ]] && echo 'Error: The ffmpeg executable was not found in $PATH' && exit 1

function convert_mp4(){
    OLD_EXT=$(sed 's|^.*\.||' <<< "$1")
    ffmpeg -i "$1" -c:v libvpx -crf 4 -q:v 10 -b:v "$BITRATE" -c:a libvorbis "${1/\.${OLD_EXT}}${NEW_EXT}"
}

if [ -n "$1" ]; then
    BITRATE="$1"
    shift
else
    echo "Error: the desired bitrate of the resulting video must be passed as the first argument"
    exit 1
fi

if [ -n "$1" ]; then
    for video in "$@"; do
        if [[ -f "$video" ]]; then
            convert_mp4 "$video"
        else
            echo "Error: no video file(s) matching '$video'"
        fi
    done
else
    for video in *.mp4; do
        convert_mp4 "$video"
    done
fi
